name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
            
    - name: Fill conf file
      run : |
            cat <<EOF > config.json
             {
              "key": "key-from-solusvm",
              "hash": "hash-from-solusvm",
              "master-url": "https://vps.dyjix.eu/api/client/command.php"
            }
            EOF
            cat config.json
            pwd
            ls -la
      
    - name: Run
      run: go run main.go help
